### ISSUE TITLE
NullReferenceException in Bugsnag.NET.Request.StackTraceLine.<Build>d__1.MoveNext()

### ISSUE THREAD

**Issue by IgorBurakov** [awseward/Bugsnag.NET#6]
I think the error might be due to a particular character in the content, but might be something else:
<pre>
System.NullReferenceException: Object reference not set to an instance of an object.
   at Bugsnag.NET.Request.StackTraceLine.<Build>d__1.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Bugsnag.NET.BugsnagSender.Send(INotice notice, Boolean useSSL)
</pre>

The error that is tried to be reported to Bugsnag:
<pre>
System.Exception: An internal error is occurred. The cause of the error has been forwarded to the technical support staff, and will be followed-up upon. ---> System.Exception: Debug Info: 
tryCount=0: 
System.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_yyyyyyyyy_tblyyyyyyy". The conflict occurred in database "yyyyyyyy", table "tblyyyyyy", column 'yyyyyy'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.<QueryImpl>d__61`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute8[T0,T1,T2,T3,T4,T5,T6,T7,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at Roadmap.DataSqlServer.RoadmapSqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at Roadmap.DataSqlServer.RoadmapSqlMapper.<>c__DisplayClass4`1.<Query>b__3()
   at Roadmap.DataSqlServer.DeadlockRetryUtil.DeadlockRetryHelper[T](Func`1 repositoryMethod)
ClientConnectionId:b01c94d2-f20d-4603-a359-081663474a4e
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Roadmap.DataSqlServer.DeadlockRetryUtil.DeadlockRetryHelper[T](Func`1 repositoryMethod)
   at Roadmap.DataSqlServer.Payment.DataAmazonPayment.Add(AmazonTransactionHistoryModel item)
   at Roadmap.RepoLayer.Payment.RepoPayment.Add(AmazonTransactionHistoryModel item)
   at Roadmap.Web.ipn.Page_Load(Object sender, EventArgs e)

--- Session Info ---
SessionID: hkvyfbzid1k052lx4c1smdtr
IsNewSession: True
Items Count: 1
Items: 
    SessionStart: 5/18/2015 12:00:08 AM
</pre>

**Comment by IgorBurakov** [comment]
I think I know the reason of the error. There is a couple of lines in the stack that are not parsed ok:
<pre>ClientConnectionId:b01c94d2-f20d-4603-a359-081663474a4e
Error Number:547,State:0,Class:16</pre>
They are result of  System.Data.SqlClient.SqlException.ToString() method that we append to the internal custom error message itself delimited with Environment.NewLine separator and they should appear in the Message section - not in the Stack

**Comment by mglodack** [comment]
@IgorBurakov New nuget package is up with your change.

- https://www.nuget.org/packages/Bugsnag.NET/
